apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: servicebinding-rds-endpoint-demo
spec:
  bindAsFiles: true
  services:
    - group: rds.services.k8s.aws
      version: v1alpha1
      kind: DBInstance
      name: {{ .Values.dbinstance.name }}
  application:
    labelSelector:
      matchLabels:
        psql.provider: aws
    version: v1
    group: apps
    resource: deployments
