apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backingservice-read-access-for-service-binding
  labels:
    servicebinding.io/controller: "true"
rules:
  - apiGroups: ["rds.services.k8s.aws"]
    resources: ["dbinstances", "dbinstances/status"]
    verbs: ["get", "list", "watch"]
